export const INSTANSI: string[] = [
  'Otorita Ibu Kota Nusantara',
  'Kementerian Koordinator Bidang Politik Hukum dan Keamanan',
  'Kementerian Koordinator Bidang Perekonomian',
  'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan',
  'Kementerian Koordinator Bidang Kemaritiman dan Investasi',
  'Kementerian Dalam Negeri',
  'Kementerian Luar Negeri',
  'Kementerian Pertahanan',
  'Kementerian Agama',
  'Kementerian Hukum dan Hak Asasi Manusia',
  'Kementerian Keuangan',
  'Kementerian Energi dan Sumber Daya Mineral',
  'Kementerian Perindustrian',
  'Kementerian Perdagangan',
  'Kementerian Pertanian',
  'Kementerian Kesehatan',
  'Kementerian Sosial',
  'Kementerian Ketenagakerjaan',
  'Kementerian Perhubungan',
  'Kementerian Pekerjaan Umum dan Perumahan Rakyat',
  'Kementerian Pendidikan Kebudayaan Riset dan Teknologi',
  'Kementerian Komunikasi dan Informatika',
  'Kementerian Lingkungan Hidup dan Kehutanan',
  'Kementerian Kelautan dan Perikanan',
  'Kementerian Agraria dan Tata Ruang / BPN',
  'Kementerian Desa Pembangunan Daerah Tertinggal dan Transmigrasi',
  'Kementerian Pemuda dan Olahraga',
  'Kementerian Pariwisata dan Ekonomi Kreatif',
  'Kementerian Investasi / BKPM',
  'Kementerian Perencanaan Pembangunan Nasional / Bappenas',
  'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi',
  'Kementerian Sekretariat Negara',
  'Kementerian Badan Usaha Milik Negara',
  'Kementerian Koperasi dan Usaha Kecil dan Menengah',
  'Kementerian Pemberdayaan Perempuan dan Perlindungan Anak',
  'Sekretariat Jenderal MPR RI',
  'Sekretariat Jenderal DPR RI',
  'Sekretariat Jenderal DPD RI',
  'Mahkamah Agung',
  'Mahkamah Konstitusi',
  'Komisi Yudisial',
  'Komisi Pemilihan Umum',
  'Badan Pengawas Pemilihan Umum',
  'Komisi Pemberantasan Korupsi',
  'Komisi Nasional Hak Asasi Manusia',
  'Kejaksaan Agung RI',
  'Badan Kepegawaian Negara',
  'Badan Pusat Statistik',
  'Badan Pengawas Obat dan Makanan',
  'Badan Pengawasan Keuangan dan Pembangunan',
  'Badan Nasional Pencarian dan Pertolongan (Basarnas)',
  'Badan Narkotika Nasional',
  'Badan Intelijen Negara',
  'Badan Siber dan Sandi Negara',
  'Arsip Nasional Republik Indonesia',
  'Badan Informasi Geospasial',
  'Badan Kependudukan dan Keluarga Berencana Nasional',
  'Perpustakaan Nasional Republik Indonesia',
  'Lembaga Administrasi Negara',
  'Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah',
  'Badan Pangan Nasional',
  'Kawasan Ekonomi Khusus',
  'Badan Riset dan Inovasi Nasional',
  'Lembaga Ilmu Pengetahuan Indonesia (bergabung ke BRIN)',
  'Badan Nasional Penanggulangan Bencana',
  'Badan Nasional Penanggulangan Terorisme',
  'Komisi Pengawas Persaingan Usaha',
  'Ombudsman Republik Indonesia',
  'Badan Pengawas Tenaga Nuklir',
  'Pemerintah Provinsi Aceh',
  'Pemerintah Provinsi Sumatera Utara',
  'Pemerintah Provinsi Sumatera Barat',
  'Pemerintah Provinsi Riau',
  'Pemerintah Provinsi Kepulauan Riau',
  'Pemerintah Provinsi Jambi',
  'Pemerintah Provinsi Sumatera Selatan',
  'Pemerintah Provinsi Kepulauan Bangka Belitung',
  'Pemerintah Provinsi Bengkulu',
  'Pemerintah Provinsi Lampung',
  'Pemerintah Provinsi Daerah Khusus Jakarta',
  'Pemerintah Provinsi Jawa Barat',
  'Pemerintah Provinsi Jawa Tengah',
  'Pemerintah Provinsi Daerah Istimewa Yogyakarta',
  'Pemerintah Provinsi Jawa Timur',
  'Pemerintah Provinsi Banten',
  'Pemerintah Provinsi Bali',
  'Pemerintah Provinsi Nusa Tenggara Barat',
  'Pemerintah Provinsi Nusa Tenggara Timur',
  'Pemerintah Provinsi Kalimantan Barat',
  'Pemerintah Provinsi Kalimantan Tengah',
  'Pemerintah Provinsi Kalimantan Selatan',
  'Pemerintah Provinsi Kalimantan Timur',
  'Pemerintah Provinsi Kalimantan Utara',
  'Pemerintah Provinsi Sulawesi Utara',
  'Pemerintah Provinsi Sulawesi Tengah',
  'Pemerintah Provinsi Sulawesi Selatan',
  'Pemerintah Provinsi Sulawesi Tenggara',
  'Pemerintah Provinsi Sulawesi Barat',
  'Pemerintah Provinsi Gorontalo',
  'Pemerintah Provinsi Maluku',
  'Pemerintah Provinsi Maluku Utara',
  'Pemerintah Provinsi Papua',
  'Pemerintah Provinsi Papua Barat',
  'Pemerintah Provinsi Papua Selatan',
  'Pemerintah Provinsi Papua Tengah',
  'Pemerintah Provinsi Papua Pegunungan',
  'Pemerintah Provinsi Papua Barat Daya',
  'Kota Banda Aceh',
  'Kabupaten Aceh Besar',
  'Kabupaten Aceh Tengah',
  'Kabupaten Aceh Selatan',
  'Kabupaten Aceh Tamiang',
  'Kabupaten Pidie',
  'Kota Medan',
  'Kota Pematangsiantar',
  'Kota Tebing Tinggi',
  'Kabupaten Deli Serdang',
  'Kabupaten Langkat',
  'Kabupaten Tapanuli Selatan',
  'Kabupaten Tapanuli Tengah',
  'Kabupaten Nias',
  'Kota Padang',
  'Kota Bukittinggi',
  'Kota Pariaman',
  'Kabupaten Agam',
  'Kabupaten Solok',
  'Kabupaten Pasaman Barat',
  'Kota Pekanbaru',
  'Kota Dumai',
  'Kabupaten Rokan Hulu',
  'Kabupaten Bengkalis',
  'Kabupaten Indragiri Hulu',
  'Kota Batam',
  'Kota Tanjungpinang',
  'Kabupaten Bintan',
  'Kabupaten Karimun',
  'Kota Jambi',
  'Kabupaten Bungo',
  'Kabupaten Merangin',
  'Kota Palembang',
  'Kota Prabumulih',
  'Kabupaten Ogan Ilir',
  'Kabupaten Musi Banyuasin',
  'Kabupaten OKU Timur',
  'Kota Pangkalpinang',
  'Kabupaten Bangka',
  'Kabupaten Belitung',
  'Kota Bengkulu',
  'Kabupaten Bengkulu Tengah',
  'Kabupaten Lebong',
  'Kota Bandar Lampung',
  'Kota Metro',
  'Kabupaten Lampung Tengah',
  'Kabupaten Lampung Selatan',
  'Kabupaten Pringsewu',
  'Kota Bogor',
  'Kota Depok',
  'Kota Bekasi',
  'Kota Bandung',
  'Kota Cimahi',
  'Kota Tasikmalaya',
  'Kota Cirebon',
  'Kabupaten Bogor',
  'Kabupaten Bekasi',
  'Kabupaten Karawang',
  'Kabupaten Subang',
  'Kabupaten Garut',
  'Kabupaten Ciamis',
  'Kabupaten Pangandaran',
  'Kota Semarang',
  'Kota Surakarta',
  'Kota Salatiga',
  'Kota Magelang',
  'Kota Pekalongan',
  'Kota Tegal',
  'Kabupaten Semarang',
  'Kabupaten Demak',
  'Kabupaten Kendal',
  'Kabupaten Banyumas',
  'Kabupaten Cilacap',
  'Kabupaten Kebumen',
  'Kabupaten Purworejo',
  'Kabupaten Wonosobo',
  'Kabupaten Boyolali',
  'Kabupaten Klaten',
  'Kabupaten Sukoharjo',
  'Kabupaten Wonogiri',
  'Kabupaten Karanganyar',
  'Kabupaten Sragen',
  'Kota Yogyakarta',
  'Kabupaten Sleman',
  'Kabupaten Bantul',
  'Kabupaten Gunung Kidul',
  'Kabupaten Kulon Progo',
  'Kota Surabaya',
  'Kota Malang',
  'Kota Kediri',
  'Kota Blitar',
  'Kota Mojokerto',
  'Kota Madiun',
  'Kota Probolinggo',
  'Kota Pasuruan',
  'Kabupaten Gresik',
  'Kabupaten Sidoarjo',
  'Kabupaten Mojokerto',
  'Kabupaten Jombang',
  'Kabupaten Madiun',
  'Kabupaten Bojonegoro',
  'Kabupaten Tuban',
  'Kabupaten Lamongan',
  'Kabupaten Barito Utara',
  'Kota Serang',
  'Kota Tangerang',
  'Kota Tangerang Selatan',
  'Kota Cilegon',
  'Kabupaten Tangerang',
  'Kabupaten Serang',
  'Kabupaten Lebak',
  'Kabupaten Pandeglang',
  'Kota Denpasar',
  'Kabupaten Badung',
  'Kabupaten Gianyar',
  'Kabupaten Buleleng',
  'Kabupaten Bangli',
  'Kabupaten Karangasem',
  'Kabupaten Klungkung',
  'Kabupaten Tabanan',
  'Kabupaten Jembrana',
  'Kota Mataram',
  'Kabupaten Lombok Barat',
  'Kabupaten Lombok Tengah',
  'Kabupaten Lombok Timur',
  'Kabupaten Lombok Utara',
  'Kabupaten Sumbawa',
  'Kabupaten Dompu',
  'Kabupaten Bima',
  'Kota Kupang',
  'Kabupaten Kupang',
  'Kabupaten Lembata',
  'Kabupaten Ende',
  'Kabupaten Flores Timur',
  'Kabupaten Manggarai',
  'Kabupaten Manggarai Barat',
  'Kota Pontianak',
  'Kota Singkawang',
  'Kabupaten Kapuas Hulu',
  'Kabupaten Ketapang',
  'Kabupaten Sambas',
  'Kabupaten Mempawah',
  'Kota Palangkaraya',
  'Kabupaten Kotawaringin Barat',
  'Kabupaten Barito Selatan',
  'Kota Banjarmasin',
  'Kota Banjarbaru',
  'Kabupaten Tanah Laut',
  'Kabupaten Banjar',
  'Kabupaten Hulu Sungai Utara',
  'Kota Balikpapan',
  'Kota Samarinda',
  'Kota Bontang',
  'Kabupaten Kutai Kartanegara',
  'Kabupaten Berau',
  'Kabupaten Penajam Paser Utara',
  'Kota Tarakan',
  'Kabupaten Bulungan',
  'Kota Manado',
  'Kota Tomohon',
  'Kota Bitung',
  'Kabupaten Minahasa',
  'Kabupaten Bolaang Mongondow',
  'Kota Palu',
  'Kabupaten Donggala',
  'Kabupaten Tolitoli',
  'Kabupaten Morowali',
  'Kabupaten Banggai',
  'Kota Makassar',
  'Kota Parepare',
  'Kota Palopo',
  'Kabupaten Gowa',
  'Kabupaten Bone',
  'Kabupaten Maros',
  'Kabupaten Pangkajene dan Kepulauan',
  'Kabupaten Wajo',
  'Kabupaten Luwu',
  'Kabupaten Luwu Timur',
  'Kota Kendari',
  'Kabupaten Konawe',
  'Kabupaten Kolaka',
  'Kabupaten Buton',
  'Kota Bau-Bau',
  'Kota Mamuju',
  'Kabupaten Mamuju Tengah',
  'Kabupaten Polewali Mandar',
  'Kota Gorontalo',
  'Kabupaten Gorontalo',
  'Kabupaten Gorontalo Utara',
  'Kota Ambon',
  'Kabupaten Maluku Tengah',
  'Kabupaten Buru',
  'Kabupaten Kepulauan Aru',
  'Kota Ternate',
  'Kota Tidore Kepulauan',
  'Kabupaten Halmahera Barat',
  'Kabupaten Halmahera Utara',
  'Kota Jayapura',
  'Kabupaten Jayapura',
  'Kabupaten Merauke',
  'Kabupaten Biak Numfor',
  'Kabupaten Nabire',
  'Kabupaten Mimika',
  'Kabupaten Jayawijaya',
  'Kabupaten Sorong',
  'Kota Sorong',
  'Kabupaten Sorong Selatan',
  'Kabupaten Manokwari',
  'Kabupaten Fakfak',
  'Kabupaten Teluk Bintuni',
];
